### ISSUE TITLE
Compatibility between ngx-modialog and  Bootstrap 4

### ISSUE THREAD

**Issue by fsebbah** [chandermani/angular6byexample#2]
Available at 3.4 branch
The component ngx-modialog and  Bootstrap4 are not compatibles.
It's important to add in the video-dialog.component.tx these:
`import {BSModalContext, bootstrap4Mode} from 'ngx-modialog/plugins/bootstrap';`
and before the declaration `@Component({}}`, you add:
`bootstrap4Mode();`
For a complete sample : [http://next.plnkr.co/edit/lV7zsw7Yqossgs9JOfQU?p=preview&preview](http://next.plnkr.co/edit/lV7zsw7Yqossgs9JOfQU?p=preview&preview)

**Comment by chandermani** [comment]
Added bootstrap4Mode, but it worked without that too, with custom css d80f42256160522f5af6e21d7c086bd689ca461b
