### ISSUE TITLE
typo

### ISSUE THREAD

**Issue by kajackdfw** [chandermani/angular6byexample#4]
Line 2 should have 2 dots before /model
from '../model';

**Comment by kajackdfw** [comment]
file : angular6byexample/trainer/src/app/workout-runner/workout-runner.component.ts

**Comment by chandermani** [comment]
Can you please let me know if this issue in the code or the text? Which chapter/checkpoint?

**Comment by kajackdfw** [comment]
The typo in in the source code for file trainer/src/app/workout-runner/workout-runner.component.ts. Line 2 should have 2 dots before /model from '../model'; The book text is correct.

**Comment by kajackdfw** [comment]
![typo](https://user-images.githubusercontent.com/554317/43466771-e156de92-94a5-11e8-962e-c2c1c33daccc.png)

**Comment by chandermani** [comment]
For `checkpoint2.1` the model class is in the same folder as workout-runner hence `./model` is correct. In later chapters/checkpoints the model class is moved.
